### ISSUE TITLE
program is very slow all the time it is stuck

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#540]
**Summary**
program is very slow all the time it is stuck
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional): Critical

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/232772675-891785a2-97cb-41c7-aa1d-0bbc4babfba1.png)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
same as it was before

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSSv7 build 7.0.402. Please verify.

**Comment by bakuradzebakuradze** [comment]
same as it was before, the issue is not resolved 
Severity: Critical

**Comment by herashchenkoa** [comment]
The issue has been reviewed and addressed. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The speed of the program has been relatively improved, This issue is closed
