### ISSUE TITLE
 A case of salmonellosis> Clinical Information - Facility Details > The primary hospitalization does not actually transfer.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#651]
**Summary**
 A case of salmonellosis Clinical Information - Facility Details > The primary hospitalization does not actually transfer.  
Name and surname of the patient "ლომიძე მარიამ" 6 წლის

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 
Severity (MANDATORY): major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/d985acb5-a830-46ab-ae86-83e418fe689b)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/acf2a7e9-8caa-4c3d-8694-66ca2d5d6973)

**Additional context**

**Comment by Talgat1989** [comment]
not fixed. "Facility patient first sought care field's data is not transfered from v6.1 to v.7
![2023-11-08_11-48-56](https://github.com/EIDSS/EIDSS7/assets/117969735/99298420-bc73-4343-8cf5-bcc4b1d786cc)

**Comment by bakuradzebakuradze** [comment]
The issue has been resolved

**Comment by herashchenkoa** [comment]
This one is a duplicate of #857.

**Comment by herashchenkoa** [comment]
This issue still exists. It will be fixed as part of further Releases.
