### ISSUE TITLE
During the process of remembering contacts (the system would freeze or the information of the entered and remembered person would not appear at first, so that we could add/select them as a contact. Also, sometimes when adding a second person to the contacts, the information of the first contact is replaced by the newly added contact and appears as two identical contacts

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#791]
**Summary**
During the process of remembering contacts (the system would freeze or the information of the entered and remembered person would not appear at first, so that we could add/select them as a contact. Also, sometimes when adding a second person to the contacts, the information of the first contact is replaced by the newly added contact and appears as two identical contacts
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/e214f104-f14d-491a-9bd5-a8ca5c78bfb2)

**Additional context**

**Comment by bakuradzebakuradze** [comment]
Severity (MANDATORY): high

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.427. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is not resolved
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/f689aec8-ce4e-4acb-abc5-abf3eafbdf31)

**Comment by herashchenkoa** [comment]
Can you please provide the exact steps that you are performing? Do you add 2 different persons from the existing list of persons or do you create new?

**Comment by bakuradzebakuradze** [comment]
in both cases Adds the same personalities
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/20f4492e-ff4a-4547-b9dc-0f6d9c0776fc)

**Comment by herashchenkoa** [comment]
Based on the user's feedback, the issue exists that the system allows to add the same person as a contact. For this issue there is a separate bug #799. The current bug is closing, the remaining issue will be covered in 799.
