### ISSUE TITLE
In the contact information field - "connection" chooses the information itself, and in English, for example: Family, Other

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#796]
**Summary**
In the contact information field - "connection" chooses the information itself, and in English, for example, Family, Other
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: maka tsilosani
Build: 
Severity (MANDATORY): Major

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/1514c20d-73c8-48de-8fa8-59b7ce34d2b4)

**Additional context**

**Comment by herashchenkoa** [comment]
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is not resolved
<img width="926" alt="Screenshot 2023-12-22 000846" src="https://github.com/EIDSS/EIDSS7/assets/128576431/9ae0abb4-d6c9-4a5a-8d5d-a683b3cf8cff">

**Comment by bakuradzebakuradze** [comment]
<img width="922" alt="Screenshot 2023-12-22 001214" src="https://github.com/EIDSS/EIDSS7/assets/128576431/5e1fa974-cd0a-43a2-b173-1af81d8f0ab0">

**Comment by TulendinovT** [comment]
Could you please retest it

**Comment by bakuradzebakuradze** [comment]
The issue is closed
